{ "employees" : [
		{
			"id"			: "0",
			"name" 		    : "Luis Espinal",
			"title"		    : "WEB DESIGNER / DEVELOPER",
			"sub_title"	    : ["UX / UI Ninja", "blue"],
			"skills"		: ["JS", "Android", "NodeJS", "AngularJS", "ExpressJS", "Adobe Suite", "UX/UI", "PM", "SASS", "gitHub", "Single-Page", "SQL"],
			"count"		    : "+19",
			"description"	: "Luis is a UX/UI designer with an impressive portfolio behind him.",
			"quote"		    : "I really enjoy conceptualizing, designing and building interactive and engaging products. For me, user experience (UX) and user  interface (UI) are the most  critical aspects of any  interactive product.",
			"available"	    : true,
			"price"		    : 55
		},
		{
			"id"			: "1",
			"name" 		    : "Nilka Santamaria",
			"title"		    : "DESIGNER",
			"sub_title"	    : ["Butterfly Mode", "green"],
			"skills"		: ["Adobe", "android", "iOS", "HTML", "Marketing", "Typography", "Sketch", "Print" ],
			"count"		    : "+17",
			"description"	: "Nilka is an android and iOS developer and designer who worked at Apple for 6 years",
			"quote"		    : "Simplicity is the key note to all true elegance.",
			"available"	    : true,
			"price"		    : 45
		},
		{
			"id"			: "2",
			"name" 		    : "Alexandra",
			"title"		    : "PHOTOGRAPHER",
			"sub_title"	    : ["The Perfect Shot", "green"],
			"skills"		: ["studio", "creative", "lighting", "composites", "on-location", "capture", "manipulation", "color-correction", "director"],
			"count"		    : "+19",
			"description"	: "Alexandra is collaborates directly with creative agencies / marketing firms",
			"quote"		    : "I will stop wearing black when they invent a darker colour.",
			"available"	    : true,
			"price"		    : 50
		},
		{
			"id"			: "3",
			"name" 		    : "Kyle David",
			"title"		    : "GRAPHIC DESIGNER",
			"sub_title"	    : ["It's not perfect yet!", "green"],
			"skills"		: ["color", "artistic", "animation", "2D", "3D", "suite", "layout", "composition", "interactive", "print", "media", "digital", "video"],
			"count"		    : "+18",
			"description"	: "Freelance graphic and web designer with an awesome portfolio in 2D/3D animation",
			"quote"		    : "Color is the thing I'm best known for. Art is what you see.",
			"available"	    : true,
			"price"		    : 65
		},
		{
			"id"			: "4",
			"name" 		    : "Luis De Jesus",
			"title"		    : "3D ARTISTS",
			"sub_title"	    : ["It's alive!", "green"],
			"skills"		: ["zBrush", "motion", "gaming", "animation", "rigging", "wireframe", "texture", "artist", "modeling", "rendering", "facial", "character"],
			"count"		    : "+12",
			"description"	: "3D modeler / animator who specializes in location and mechanical design",
			"quote"		    : "The details are not the details. They make the design and bring live to static.",
			"available"	    : true,
			"price"		    : 45
		},
		{
			"id"			: "5",
			"name" 		    : "Xayanna Alexia",
			"title"		    : "PROGRAMMER",
			"sub_title"	    : ["Give me a challenge!", "green"],
			"skills"		: ["script", "web", "php", "js", "apps", "native", "iOS", "java", "perl", "frameworks", "front-end", "back-end", "database", "server", "cloud"],
			"count"		    : "+16",
			"description"	: "Super-fast code-ninja who prototypes as fast as we brainstorm",
			"quote"		    : "You ever had that feeling that right now is one of those moments when we are influencing the future.",
			"available"	    : true,
			"price"		    : 75
		},
		{
			"id"			: "6",
			"name" 		    : "Paul Johnson",
			"title"		    : "DESIGNER / DEVELOPER",
			"sub_title"	    : ["Bring it!", "blue"],
			"skills"		: ["JS", "Android", "NodeJS", "AngularJS", "ExpressJS", "Adobe Suite", "UX/UI", "PM", "SASS", "gitHub", "Single-Page", "SQL"],
			"count"		    : "+19",
			"description"	: "UX/UI designer with an impressive portfolio behind him.",
			"quote"		    : "I really enjoy conceptualizing, designing and building interactive and engaging products. For me, user experience (UX) and user  interface (UI) are the most  critical aspects of any  interactive product.",
			"available"	    : true,
			"price"		    : 65
		},
		{
			"id"			: "7",
			"name" 		    : "Nieta Amarilla",
			"title"		    : "DESIGNER",
			"sub_title"	    : ["Butterfly Mode", "green"],
			"skills"		: ["Adobe", "android", "iOS", "HTML", "Marketing", "Typography", "Sketch", "Print" ],
			"count"		    : "+17",
			"description"	: "Android and iOS developer and designer who worked at Apple for 6 years",
			"quote"		    : "Simplicity is the key note to all true elegance.",
			"available"	    : true,
			"price"		    : 35
		},
		{
			"id"			: "8",
			"name" 		    : "Saul Morgan",
			"title"		    : "PHOTOGRAPHER",
			"sub_title"	    : ["The Perfect Shot", "green"],
			"skills"		: ["studio", "creative", "lighting", "composites", "on-location", "capture", "manipulation", "color-correction", "director"],
			"count"		    : "+19",
			"description"	: "Collaborates directly with creative agencies / marketing firms",
			"quote"		    : "I will stop wearing black when they invent a darker colour.",
			"available"	    : true,
			"price"		    : 40
		},
		{
			"id"			: "9",
			"name" 		    : "Ben Rosen",
			"title"		    : "GRAPHIC DESIGNER",
			"sub_title"	    : ["It's not perfect yet!", "green"],
			"skills"		: ["color", "artistic", "technical", "animation", "2D", "3D", "suite", "layout", "composition", "interactive", "print", "media"],
			"count"		    : "+18",
			"description"	: "Freelance graphic and web designer with an awesome portfolio in 2D/3D animation",
			"quote"		    : "Color is the thing I'm best known for. Art is what you see.",
			"available"	    : true,
			"price"		    : 50
		},
		{
			"id"			: "10",
			"name" 		    : "Andrew Rosen",
			"title"		    : "3D ARTISTS",
			"sub_title"	    : ["It's alive!", "green"],
			"skills"		: ["zBrush", "motion", "gaming", "animation", "rigging", "wireframe", "texture", "artist", "modeling", "rendering", "facial"],
			"count"		    : "+12",
			"description"	: "3D modeler / animator who specializes in location and mechanical design",
			"quote"		    : "The details are not the details. They make the design and bring live to static.",
			"available"	    : true,
			"price"		    : 80
		},
		{
			"id"			: "11",
			"name" 		    : "Peter Thomas",
			"title"		    : "PROGRAMMER",
			"sub_title"	    : ["Give me a challenge!", "green"],
			"skills"		: ["script", "web", "php", "js", "apps", "native", "iOS", "java", "perl", "frameworks", "front-end", "back-end", "database", "server", "cloud"],
			"count"		    : "+16",
			"description"	: "Super-fast code-ninja who prototypes as fast as we brainstorm",
			"quote"		    : "You ever had that feeling that right now is one of those moments when we are influencing the future.",
			"available"	    : true,
			"price"		    : 65
		}
]}